general.import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
]

[window]
padding.x = 30
padding.y = 30
title = "in love with the golden since april"

dimensions = { columns = 100, lines = 23 }
decorations = "Buttonless"

opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono"
size = 14
offset = { x = 0, y = 2 }

[cursor]
style = { blinking = "On" }
blink_interval = 200
thickness = 0.2

[mouse]
hide_when_typing = true
