[tools]
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tokei" = "latest"
"cargo:trimsec" = "latest"
"cargo:zoxide" = "latest"
flutter = "latest"
ruby = "latest"
